import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Data.Finsupp.Basic

/-!
# Connes-Kreimer M0 primitives

This file contains only the closed-proof, type-parametric M0 core.  It does not
choose or duplicate a rooted-tree type.  A future tree package supplies the
index type `Tree` and a vertex-count function.

References:
* A. Connes and D. Kreimer, 1998, "Hopf algebras, renormalization and
  noncommutative geometry", Communications in Mathematical Physics 199.
* A. Connes and D. Kreimer, 2000, "Renormalization in quantum field theory
  and the Riemann-Hilbert problem I", Communications in Mathematical Physics
  210.
-/

noncomputable section

namespace ConnesKreimer

universe u v

/-- A forest is a finite multiset of rooted trees, represented as multiplicities.

This is deliberately parametric in `Tree`; the project must reuse an external
rooted-tree type rather than defining a competing one here. -/
abbrev Forest (Tree : Type u) : Type u :=
  Finsupp Tree Nat

/-- The free commutative algebra generated by rooted trees.

Mathematically this is the polynomial algebra `R[Tree]`; monomials are forests.
-/
abbrev CKAlgebra (R : Type v) (Tree : Type u) [CommSemiring R] : Type (max u v) :=
  MvPolynomial Tree R

/-- The generator corresponding to one rooted tree. -/
def treeGenerator (R : Type v) {Tree : Type u} [CommSemiring R] (t : Tree) :
    CKAlgebra R Tree :=
  MvPolynomial.X t

/-- The monomial corresponding to a forest. -/
def forestMonomial (R : Type v) {Tree : Type u} [CommSemiring R] (f : Forest Tree) :
    CKAlgebra R Tree :=
  MvPolynomial.monomial f 1

@[simp]
theorem treeGenerator_eq_forestMonomial_single_one {Tree : Type u} {R : Type v}
    [CommSemiring R] (t : Tree) :
    treeGenerator R t = forestMonomial R (Finsupp.single t 1 : Forest Tree) := by
  rfl

/-- Vertex count of a forest, once a vertex count on trees is supplied. -/
def Forest.vertexCount {Tree : Type u} (vertices : Tree -> Nat) (f : Forest Tree) : Nat :=
  f.sum fun t multiplicity => multiplicity * vertices t

@[simp]
theorem Forest.vertexCount_zero {Tree : Type u} (vertices : Tree -> Nat) :
    Forest.vertexCount vertices (0 : Forest Tree) = 0 := by
  simp [Forest.vertexCount]

/-- A polynomial is homogeneous of vertex degree `n` when every nonzero monomial
has forest vertex count `n`.  This records the intended M0 grading datum without
claiming a completed Mathlib `GradedAlgebra` instance. -/
def IsHomogeneousVertexDegree {R : Type v} {Tree : Type u} [CommSemiring R]
    (vertices : Tree -> Nat) (n : Nat) (p : CKAlgebra R Tree) : Prop :=
  forall f : Forest Tree, MvPolynomial.coeff f p ≠ 0 -> Forest.vertexCount vertices f = n

@[simp]
theorem isHomogeneousVertexDegree_zero {R : Type v} {Tree : Type u} [CommSemiring R]
    (vertices : Tree -> Nat) (n : Nat) :
    IsHomogeneousVertexDegree (R := R) vertices n (0 : CKAlgebra R Tree) := by
  intro f hf
  simp at hf

end ConnesKreimer
